-- Seed 初始資料
-- 用於開發測試的基礎資料

-- Note:
-- - 假設 migrations 已建立 tables。
-- - 本檔案僅提供「最小可用」的示範資料，讓新使用者一進來就看得懂資料長相。

-- 插入預設使用者（MVP 單人模式）
INSERT OR IGNORE INTO users (id, email, password_hash, created_at, updated_at)
VALUES ('user-001', 'demo@duellog.com', 'placeholder_hash', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 插入遊戲：Yu-Gi-Oh! Master Duel
INSERT OR IGNORE INTO games (id, key, name)
VALUES ('game-md', 'master_duel', 'Yu-Gi-Oh! Master Duel');

-- 插入牌組模板（前端下拉選項用；theme 可之後在 UI 調整）
-- main：主軸，sub：副軸
INSERT OR IGNORE INTO deck_templates (id, game_id, main, theme, deck_type) VALUES
  ('tpl-auto-e5860cb2', 'game-md', 'DDD', '超量', 'main'),
  ('tpl-auto-a4c5a59a', 'game-md', 'FTK', '無', 'main'),
  ('tpl-auto-c82dcfe0', 'game-md', 'HERO', '融合', 'main'),
  ('tpl-auto-5e50fe2c', 'game-md', 'LL', '超量', 'main'),
  ('tpl-auto-ad5f2639', 'game-md', 'Meta Beat', '陷阱', 'main'),
  ('tpl-auto-1fcedbf0', 'game-md', 'R-ACE', '連結', 'main'),
  ('tpl-auto-810720d3', 'game-md', 'RR', '超量', 'main'),
  ('tpl-auto-e8642bcf', 'game-md', 'TestMy', '無', 'main'),
  ('tpl-auto-391747ba', 'game-md', 'TestOpp', '無', 'main'),
  ('tpl-auto-447e132b', 'game-md', 'Unknown', '無', 'main'),
  ('tpl-auto-8bc4a0c7', 'game-md', 'VS', '連結', 'main'),
  ('tpl-auto-99af7f21', 'game-md', 'spyral', '連結', 'main'),
  ('tpl-auto-a5d04811', 'game-md', '伊格尼斯', '連結', 'main'),
  ('tpl-auto-d8656228', 'game-md', '伍世壞', '同步', 'main'),
  ('tpl-auto-30ce39e2', 'game-md', '偉魔', '輔助', 'main'),
  ('tpl-auto-47e7bffa', 'game-md', '光道', '連結', 'main'),
  ('tpl-auto-3f3d82d3', 'game-md', '六世壞', '超量', 'main'),
  ('tpl-auto-2fdb4917', 'game-md', '六武眾', '同步', 'main'),
  ('tpl-auto-7f9adb43', 'game-md', '六花', '連結', 'main'),
  ('tpl-auto-f32b7ff2', 'game-md', '再世', '輔助', 'main'),
  ('tpl-auto-d9cde974', 'game-md', '冰結界', '同步', 'main'),
  ('tpl-auto-b5b06280', 'game-md', '利希德', '陷阱', 'main'),
  ('tpl-auto-ed4c221c', 'game-md', '刻魔', '輔助', 'main'),
  ('tpl-auto-69f78e74', 'game-md', '刻魔聖徒', '輔助', 'main'),
  ('tpl-auto-32c6a742', 'game-md', '勇者', '輔助', 'main'),
  ('tpl-auto-6bd46f12', 'game-md', '十二獸', '超量', 'main'),
  ('tpl-auto-b919fd88', 'game-md', '千年', '融合', 'main'),
  ('tpl-auto-50c31b3c', 'game-md', '卡通', '輔助', 'main'),
  ('tpl-auto-e30472ce', 'game-md', '原石', '輔助', 'main'),
  ('tpl-auto-6bcf1155', 'game-md', '原質', '融合', 'main'),
  ('tpl-auto-ba3b6c82', 'game-md', '古巨基', '融合', 'main'),
  ('tpl-auto-1c3479f7', 'game-md', '古生物', '陷阱', 'main'),
  ('tpl-auto-d18f7a8a', 'game-md', '同步GS', '同步', 'main'),
  ('tpl-auto-eac3065e', 'game-md', '吸血鬼', '超量', 'main'),
  ('tpl-auto-9a54ae40', 'game-md', '地縛', '融合', 'main'),
  ('tpl-auto-08aa8dc5', 'game-md', '堆墓GS', '無', 'main'),
  ('tpl-auto-b8c196f2', 'game-md', '大植然', '同步', 'main'),
  ('tpl-auto-b3f7ace1', 'game-md', '大法師', '無', 'main'),
  ('tpl-auto-b1e33980', 'game-md', '天琴', '連結', 'main'),
  ('tpl-auto-2e66d951', 'game-md', '天盃', '同步', 'main'),
  ('tpl-auto-52bfaa8f', 'game-md', '奇巧人偶', '超量', 'main'),
  ('tpl-auto-47f7d021', 'game-md', '奇美拉', '融合', 'main'),
  ('tpl-auto-fd689345', 'game-md', '奕勇', '鐘擺', 'main'),
  ('tpl-auto-71693329', 'game-md', '妖仙獸', '同步', 'main'),
  ('tpl-auto-85b80ab6', 'game-md', '威風魔靈', '鐘擺', 'main'),
  ('tpl-auto-03d0fc09', 'game-md', '寶石', '融合', 'main'),
  ('tpl-auto-1fe6f4bc', 'game-md', '寶箱怪', '超量', 'main'),
  ('tpl-auto-a9ca7ce8', 'game-md', '尤貝爾', '融合', 'main'),
  ('tpl-auto-be20ebec', 'game-md', '巳劍', '儀式', 'main'),
  ('tpl-auto-021d8926', 'game-md', '平行者', '輔助', 'main'),
  ('tpl-auto-20949c9a', 'game-md', '幻奏', '融合', 'main'),
  ('tpl-auto-cb704fb5', 'game-md', '影依', '融合', 'main'),
  ('tpl-auto-ef607d50', 'game-md', '征龍', '超量', 'main'),
  ('tpl-auto-2bfdd0a9', 'game-md', '御巫', '儀式', 'main'),
  ('tpl-auto-1e39888c', 'game-md', '忍者', '融合', 'main'),
  ('tpl-auto-0e3950ae', 'game-md', '恐啡肽', '陷阱', 'main'),
  ('tpl-auto-aeac9dd6', 'game-md', '恩底米翁', '鐘擺', 'main'),
  ('tpl-auto-47eef00b', 'game-md', '戰華', '輔助', 'main'),
  ('tpl-auto-8017a097', 'game-md', '擬聲', '超量', 'main'),
  ('tpl-auto-8b272892', 'game-md', '教導', '輔助', 'main'),
  ('tpl-auto-95adeba5', 'game-md', '斬機', '連結', 'main'),
  ('tpl-auto-6151cfab', 'game-md', '新潮廚師', '儀式', 'main'),
  ('tpl-auto-57fc3e45', 'game-md', '旅鳥', '魔法', 'main'),
  ('tpl-auto-52842834', 'game-md', '星塵龍', '同步', 'main'),
  ('tpl-auto-0df818d5', 'game-md', '星辰', '融合', 'main'),
  ('tpl-auto-021ac609', 'game-md', '春化精', '輔助', 'main'),
  ('tpl-auto-444198a9', 'game-md', '月光', '融合', 'main'),
  ('tpl-auto-f26d6d1a', 'game-md', '水GS', '連結', 'main'),
  ('tpl-auto-e396c679', 'game-md', '水晶機巧', '同步', 'main'),
  ('tpl-auto-1bd14074', 'game-md', '海晶', '連結', 'main'),
  ('tpl-auto-32891ffd', 'game-md', '海皇', '超量', 'main'),
  ('tpl-auto-e4572ead', 'game-md', '涅姆蕾妮婭', '鐘擺', 'main'),
  ('tpl-auto-05936bc6', 'game-md', '炎獸', '連結', 'main'),
  ('tpl-auto-f8fc585b', 'game-md', '炎王', '超量', 'main'),
  ('tpl-auto-02c22fb8', 'game-md', '烙印', '融合', 'main'),
  ('tpl-auto-bc1513fc', 'game-md', '焰聖', '同步', 'main'),
  ('tpl-auto-93f6642c', 'game-md', '煉獄機', '連結', 'main'),
  ('tpl-auto-7b1f63ea', 'game-md', '燒血', '陷阱', 'main'),
  ('tpl-auto-7689fefc', 'game-md', '珠淚', '融合', 'main'),
  ('tpl-auto-d30b01df', 'game-md', '疾行機人', '同步', 'main'),
  ('tpl-auto-8c9271b0', 'game-md', '白之森', '同步', 'main'),
  ('tpl-auto-09a62ec9', 'game-md', '白銀城', '陷阱', 'main'),
  ('tpl-auto-e894e798', 'game-md', '白龍', '融合', 'main'),
  ('tpl-auto-6cc26cc9', 'game-md', '百夫', '同步', 'main'),
  ('tpl-auto-e4e60f8a', 'game-md', '百鬼羅剎', '超量', 'main'),
  ('tpl-auto-9e0b160f', 'game-md', '相劍', '同步', 'main'),
  ('tpl-auto-f1fe9b2d', 'game-md', '真紅眼', '融合', 'main'),
  ('tpl-auto-b8ffe9b5', 'game-md', '瞳魔', '魔法', 'main'),
  ('tpl-auto-9ce2c999', 'game-md', '破械', '連結', 'main'),
  ('tpl-auto-0f2af385', 'game-md', '碼麗絲', '連結', 'main'),
  ('tpl-auto-33bdc368', 'game-md', '神碑', '魔法', 'main'),
  ('tpl-auto-11af5383', 'game-md', '神藝', '融合', 'main'),
  ('tpl-auto-9948ae3d', 'game-md', '紅惡魔龍', '同步', 'main'),
  ('tpl-auto-03607ecb', 'game-md', '純愛', '超量', 'main'),
  ('tpl-auto-edc60ae3', 'game-md', '美味', '同步', 'main'),
  ('tpl-auto-3c9bf970', 'game-md', '聖徒', '融合', 'main'),
  ('tpl-auto-2dc34288', 'game-md', '聖邪璃琴', '連結', 'main'),
  ('tpl-auto-a9cfabbf', 'game-md', '肅聲', '儀式', 'main'),
  ('tpl-auto-c99024f6', 'game-md', '荷魯斯', '輔助', 'main'),
  ('tpl-auto-72c1204d', 'game-md', '蕾禍', '連結', 'main'),
  ('tpl-auto-ab52727d', 'game-md', '蛇眼', '連結', 'main'),
  ('tpl-auto-89e513e0', 'game-md', '蟲惑魔', '陷阱', 'main'),
  ('tpl-auto-1cbe8ba7', 'game-md', '記憶物', '融合', 'main'),
  ('tpl-auto-a3c88bb7', 'game-md', '超重', '同步', 'main'),
  ('tpl-auto-3218d9ef', 'game-md', '進化恐龍', '超量', 'main'),
  ('tpl-auto-96d5ae9f', 'game-md', '銀河眼', '超量', 'main'),
  ('tpl-auto-54f2ddbf', 'game-md', '鐵獸', '連結', 'main'),
  ('tpl-auto-12fc58e2', 'game-md', '閃刀姬', '連結', 'main'),
  ('tpl-auto-2f5aa67e', 'game-md', '雙子', '連結', 'main'),
  ('tpl-auto-b002ae41', 'game-md', '雪女', '連結', 'main'),
  ('tpl-auto-db3b4c3a', 'game-md', '雷熱', '超量', 'main'),
  ('tpl-auto-11669197', 'game-md', '雷精', '連結', 'main'),
  ('tpl-auto-6667a59b', 'game-md', '雷風水', '融合', 'main'),
  ('tpl-auto-a0560a9a', 'game-md', '雷龍', '融合', 'main'),
  ('tpl-auto-4227f410', 'game-md', '電子龍', '超量', 'main'),
  ('tpl-auto-56f007e0', 'game-md', '電氣', '無', 'main'),
  ('tpl-auto-f5d2d9b1', 'game-md', '電腦堺', '同步', 'main'),
  ('tpl-auto-955e36d0', 'game-md', '霸王', '鐘擺', 'main'),
  ('tpl-auto-38378f3e', 'game-md', '靈獸', '連結', 'main'),
  ('tpl-auto-8f505b91', 'game-md', '靈魂鳥', '無', 'main'),
  ('tpl-auto-babce0db', 'game-md', '驅魔修女', '超量', 'main'),
  ('tpl-auto-cd19a4e4', 'game-md', '魔彈', '連結', 'main'),
  ('tpl-auto-87715610', 'game-md', '魔救', '同步', 'main'),
  ('tpl-auto-0bc235ba', 'game-md', '魔界劇團', '連結', 'main'),
  ('tpl-auto-b7b6776e', 'game-md', '魔術師', '鐘擺', 'main'),
  ('tpl-auto-7c54f970', 'game-md', '黃金卿', '陷阱', 'main'),
  ('tpl-auto-c68c1bfe', 'game-md', '黃金櫃', '魔法', 'main'),
  ('tpl-auto-2cba288c', 'game-md', '黑羽', '同步', 'main'),
  ('tpl-auto-0a867884', 'game-md', '黑魔導', '融合', 'main'),
  ('tpl-auto-79831f65', 'game-md', '龍女僕', '融合', 'main'),
  ('tpl-auto-eb349bfd', 'game-md', '龍華', '魔法', 'main'),
  ('tpl-auto-730d31a1', 'game-md', '龍輝巧', '儀式', 'main'),
  ('tpl-auto-2b24fcc5', 'game-md', '龐克', '同步', 'main');

-- 注意：本 seed 不會插入 decks / matches（避免把個人對局資料帶進公開 repo）。
